//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallChanger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en_AU")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en_AU")]
        public string FallbackLanguage {
            get {
                return ((string)(this["FallbackLanguage"]));
            }
            set {
                this["FallbackLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentConfig {
            get {
                return ((string)(this["CurrentConfig"]));
            }
            set {
                this["CurrentConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::SevenZip.CompressionLevel CompressionLevel {
            get {
                return ((global::SevenZip.CompressionLevel)(this["CompressionLevel"]));
            }
            set {
                this["CompressionLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fill")]
        public global::WallChanger.Wallpaper.WallpaperStyle DefaultWallpaperStyle {
            get {
                return ((global::WallChanger.Wallpaper.WallpaperStyle)(this["DefaultWallpaperStyle"]));
            }
            set {
                this["DefaultWallpaperStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultRandomise {
            get {
                return ((bool)(this["DefaultRandomise"]));
            }
            set {
                this["DefaultRandomise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultFading {
            get {
                return ((bool)(this["DefaultFading"]));
            }
            set {
                this["DefaultFading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 h")]
        public string DefaultOffset {
            get {
                return ((string)(this["DefaultOffset"]));
            }
            set {
                this["DefaultOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 m")]
        public string DefaultInterval {
            get {
                return ((string)(this["DefaultInterval"]));
            }
            set {
                this["DefaultInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Background")]
        public global::WallChanger.HighlightListBox.HighlightMode HighlightMode {
            get {
                return ((global::WallChanger.HighlightListBox.HighlightMode)(this["HighlightMode"]));
            }
            set {
                this["HighlightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveCaption")]
        public global::System.Drawing.Color HighlightColour {
            get {
                return ((global::System.Drawing.Color)(this["HighlightColour"]));
            }
            set {
                this["HighlightColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalRandomise {
            get {
                return ((bool)(this["GlobalRandomise"]));
            }
            set {
                this["GlobalRandomise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalFading {
            get {
                return ((bool)(this["GlobalFading"]));
            }
            set {
                this["GlobalFading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalWallpaperStyle {
            get {
                return ((bool)(this["GlobalWallpaperStyle"]));
            }
            set {
                this["GlobalWallpaperStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalPreProcessing {
            get {
                return ((bool)(this["GlobalPreProcessing"]));
            }
            set {
                this["GlobalPreProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultPreProcessingEnabled {
            get {
                return ((bool)(this["DefaultPreProcessingEnabled"]));
            }
            set {
                this["DefaultPreProcessingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultBrightnessEnabled {
            get {
                return ((bool)(this["DefaultBrightnessEnabled"]));
            }
            set {
                this["DefaultBrightnessEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultBrightnessValue {
            get {
                return ((int)(this["DefaultBrightnessValue"]));
            }
            set {
                this["DefaultBrightnessValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultSaturationEnabled {
            get {
                return ((bool)(this["DefaultSaturationEnabled"]));
            }
            set {
                this["DefaultSaturationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultSaturationValue {
            get {
                return ((int)(this["DefaultSaturationValue"]));
            }
            set {
                this["DefaultSaturationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultContrastEnabled {
            get {
                return ((bool)(this["DefaultContrastEnabled"]));
            }
            set {
                this["DefaultContrastEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultContrastValue {
            get {
                return ((int)(this["DefaultContrastValue"]));
            }
            set {
                this["DefaultContrastValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultHueEnabled {
            get {
                return ((bool)(this["DefaultHueEnabled"]));
            }
            set {
                this["DefaultHueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultHueValue {
            get {
                return ((int)(this["DefaultHueValue"]));
            }
            set {
                this["DefaultHueValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultGaussianBlurEnabled {
            get {
                return ((bool)(this["DefaultGaussianBlurEnabled"]));
            }
            set {
                this["DefaultGaussianBlurEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultGaussianBlurSize {
            get {
                return ((int)(this["DefaultGaussianBlurSize"]));
            }
            set {
                this["DefaultGaussianBlurSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultGaussianSharpenEnabled {
            get {
                return ((bool)(this["DefaultGaussianSharpenEnabled"]));
            }
            set {
                this["DefaultGaussianSharpenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultGaussianSharpenSize {
            get {
                return ((int)(this["DefaultGaussianSharpenSize"]));
            }
            set {
                this["DefaultGaussianSharpenSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultPixelateEnabled {
            get {
                return ((bool)(this["DefaultPixelateEnabled"]));
            }
            set {
                this["DefaultPixelateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultPixelateSize {
            get {
                return ((int)(this["DefaultPixelateSize"]));
            }
            set {
                this["DefaultPixelateSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultVignetteEnabled {
            get {
                return ((bool)(this["DefaultVignetteEnabled"]));
            }
            set {
                this["DefaultVignetteEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultVignetteColour {
            get {
                return ((global::System.Drawing.Color)(this["DefaultVignetteColour"]));
            }
            set {
                this["DefaultVignetteColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultTintEnabled {
            get {
                return ((bool)(this["DefaultTintEnabled"]));
            }
            set {
                this["DefaultTintEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultTintColour {
            get {
                return ((global::System.Drawing.Color)(this["DefaultTintColour"]));
            }
            set {
                this["DefaultTintColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultEdgeDetectionEnabled {
            get {
                return ((bool)(this["DefaultEdgeDetectionEnabled"]));
            }
            set {
                this["DefaultEdgeDetectionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KayyaliEdgeFilter")]
        public global::WallChanger.EdgeDetectionFilter DefaultEdgeDetectionFilter {
            get {
                return ((global::WallChanger.EdgeDetectionFilter)(this["DefaultEdgeDetectionFilter"]));
            }
            set {
                this["DefaultEdgeDetectionFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultImageFilterEnabled {
            get {
                return ((bool)(this["DefaultImageFilterEnabled"]));
            }
            set {
                this["DefaultImageFilterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlackWhite")]
        public global::WallChanger.ImageFilterMatrix DefaultImageFilterMatrix {
            get {
                return ((global::WallChanger.ImageFilterMatrix)(this["DefaultImageFilterMatrix"]));
            }
            set {
                this["DefaultImageFilterMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultChannelRotationEnabled {
            get {
                return ((bool)(this["DefaultChannelRotationEnabled"]));
            }
            set {
                this["DefaultChannelRotationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RotateOnce")]
        public global::WallChanger.ChannelRotation DefaultChannelRotationValue {
            get {
                return ((global::WallChanger.ChannelRotation)(this["DefaultChannelRotationValue"]));
            }
            set {
                this["DefaultChannelRotationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultColourSchemeEnabled {
            get {
                return ((bool)(this["DefaultColourSchemeEnabled"]));
            }
            set {
                this["DefaultColourSchemeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalColourSchemeEnabled {
            get {
                return ((bool)(this["GlobalColourSchemeEnabled"]));
            }
            set {
                this["GlobalColourSchemeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RainbowModeEnabled {
            get {
                return ((bool)(this["RainbowModeEnabled"]));
            }
            set {
                this["RainbowModeEnabled"] = value;
            }
        }
    }
}
